name: Override or Remove a Link
description: Submit a request to override or remove an existing link
title: "[Override Request]: "
labels: ["override link", "workflow"]
assignees:
  - dadatuputi
body:
  - type: input
    id: match
    attributes:
      label: Link ID
      description: The unique ID of the link to delete. This should be auto-filled but is also present in the html for each link as data-content-id.
      placeholder: 037a5a53-db87-48f5-8c6e-017d65bf8b3c
    validations:
      required: true
  - type: input
    id: new_title
    attributes:
      label: Link Title
      description: "New title for the link. This and / or the Link URL field must be provided."
      placeholder: AF Portal
    validations:
      required: false
  - type: input
    id: new_url
    attributes:
      label: Link URL
      description: "New URL for the link. This and / or the Link Title field must be provided."
      placeholder: https://www.my.af.mil
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: Please explain why the link changes should be approved.
    validations:
      required: true
