name: Delete a Link
description: Submit a request to delete a link
title: "[DELETE]: "
labels: ["delete link", "workflow"]
assignees:
  - dadatuputi
body:
  - type: input
    id: match
    attributes:
      label: Link ID
      description: The unique ID of the link to delete. This should be auto-filled but is also present in the html for each link as data-content-id.
      placeholder: 037a5a53-db87-48f5-8c6e-017d65bf8b3c
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: Please explain why the link changes should be approved.
    validations:
      required: true
  
