name: Override Link
description: Submit a request to override an existing link
title: "[Override Request]: "
labels: ["override request"]
assignees:
  - dadatuputi
body:
  - type: dropdown
    id: match_method
    attributes:
      label: Override Match Method
      description: >
        How to match this override to the original link:
        ContentID: Match this ContentID to target ContentID (unique to link)
        Title: Match this title to target link title
        URL: Match this URL to target link URL
        Fuzzy Title: Partially match this title to target link title
      options:
        - ContentID
        - Title
        - URL
        - Fuzzy Title
      default: 0
    validations:
      required: true
  - type: input
    id: match
    attributes:
      label: Match String
      description: The string to match, depends on Match Method above.
    validations:
      required: true
  - type: input
    id: new_title
    attributes:
      label: Link Title
      description: "**At least one of 'Link Title' or 'Link URL' must be provided**"
      placeholder: AF Portal
    validations:
      required: false
  - type: input
    id: new_url
    attributes:
      label: Link URL
      description: "**At least one of 'Link Title' or 'Link URL' must be provided**"
      placeholder: https://www.my.af.mil
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: A comment about the override and a reason why it should be added.
    validations:
      required: false
  
