name: Link Add from Issue

on:
  repository_dispatch:
    types: [link_add]
  
jobs:
  add_link:
    runs-on: ubuntu-latest
    steps:

    - name: parse_fields
      env:
        BODY: ${{ github.event.client_payload.issue_body }}
      run: |

        echo "Original issue: ${{ github.event.client_payload.original_issue }}"
        echo "Triggered by: ${{ github.event.client_payload.triggered_by }}"
        echo "Issue body: ${{ github.event.client_payload.issue_body }}"

        TITLE=$(echo "$BODY" | sed -n 3p)
        URL=$(echo "$BODY" | sed -n 7p)
        [[ -z $TITLE ]] && exit 1
        [[ -z $URL ]] && exit 1
        TITLE="TITLE=$TITLE"
        URL="URL=$URL"
        echo $TITLE | tee -a $GITHUB_ENV
        echo $URL | tee -a $GITHUB_ENV

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install jq & sponge
      run: |
        # Skip installing pacakge docs {makes the man-db trigger much faster) 
        # (I disabled `/doc` and `/info` too, just in case.)
        sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
        path-exclude /usr/share/doc/*
        path-exclude /usr/share/man/*
        path-exclude /usr/share/info/*
        EOF

        sudo apt-get update
        sudo apt-get install --yes jq moreutils

    - name: Add link to end of list
      run: |
        jq -r --arg TITLE "${{ env.TITLE }}" --arg URL "${{ env.URL }}" '.OTHER += [{"title": $TITLE,"link": $URL}]' src/links/links_other.json | sponge src/links/links_other.json
        cat src/links/links_other.json

    - name: Commit New Changes
      uses: EndBug/add-and-commit@v7
      with:
        message: Updated links from Issue

    - name: Trigger next workflow
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'build',
            client_payload: {
              commit_sha: context.sha,
              message: 'Updated links from Issue'
            }
          });

    - name: Add success comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✅ **Link added successfully!** 
            
            The link has been added and will be active on the next site deployment.
          })