name: Update on file change

on:
  push:
    paths-ignore:
      - 'docs/index.html'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.github/**'
  workflow_dispatch:

jobs:
  Update_Links:
    name: Update Links
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm ci
      - name: Check for Updated Links
        run: npm run build
      - name: Commit New Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: Updated Links By GitHub Action
