name: Combine links

on:
  push:
    paths-ignore:
      - 'docs/index.html'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.github/**'
      - '.git/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Append Link from Approved Link Request"]
    types:
      - completed

jobs:
  Update_Links:
    name: Update Links
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Check for Updated Links
        env:
          NODE_ENV: production
        run: npm run build
      - name: Commit New Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated Links By GitHub Action
