name: Update AF Links from Approved Issue

on:
  issues:
    types: [closed]
  
jobs:
  get_fields:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'update af links')
    steps:
    - name: get_fields
      run: |
        B64=$(echo "$BODY" | sed -n 3p)
        [[ -z $B64 ]] && exit 1
        B64="B64=$B64"
        echo $B64 | tr -d '[:space:]' | tee -a $GITHUB_ENV
      env:
        BODY: ${{ github.event.issue.body }}
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Overwrite links with new link list
      run: |
        JSON=$(echo "$env.B64" | base64 -d | gzip -dc)
        echo "Decompressed data:"
        echo "$JSON" | tee src/links/links_af.json
    # - name: Commit New Changes
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     message: Updated af links from Issue
